# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsLover', '0004_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='types',
            field=models.CharField(default='', max_length=20),
        ),
    ]
