# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportsLover', '0005_notification_types'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
